name: Thirst
version: 1.8.15
description: Adds a thirst mechanic into vanilla minecraft!
main: com.gamerking195.dev.thirst.Thirst
author: GamerKing195
softdepend: [PlaceholderAPI, WorldGuard, MVdWPlaceholderAPI]
website: https://www.spigotmc.org/resources/thirst.24610/
commands:
  thirst:
    description: The base ThirstManager command.
permissions:
  thirst.*:
    default: false
    description: Gives the player access to all permissions
  thirst.command:
    default: true
    description: Gives access to the command /thirst.
  thirst.command.help:
    default: true
    description: Gives access to the command /thirst help.
  thirst.command.view:
    default: true
    description: Allows a player to view THEIR thirst via /thirst view.
  thirst.command.view.other:
    default: op
    description: Allows a player to view OTHER players thirst via /thirst view [player].
  thirst.command.reload:
    default: op
    description: Gives access to the command /thirst reload.
  thirst.ignore:
    default: false
    description: Makes it so a player is not affected by thirst.
  thirst.command.list:
    default: op
    description: Gives access to the command /thirst list [Effects/Food].
  thirst.command.update:
    default: op
    description: Gives access to the command /thirst update.
  thirst.command.set:
    default: op
    description: Gives access to the command /thirst set [player] [int].
